### ISSUE TITLE
Kleinigkeiten

### ISSUE THREAD

**Issue by paintdog** [obestwalter/zu_presentations#1]
Zu: zu_presentations/pycharm/slides.md

(1) In vier Bildern erklärt, wo ich herkomme, weil das eventuell auch veranschaulicht, warum ich IDEs so gerne mag

> tippo 

(2) Ich bin kein Fan von Vim

> ich einmal eliminieren.

(3) Werkzeuge eines Softwareentwicklers (z.B. Git)

> tippo
## 

Ich habe nicht alles gelesen, nur einmal überflogen. Schöne Präsentation, ich mag PyCharm (CE) auch sehr.

**Comment by obestwalter** [comment]
Danke - typos hab ich gefixt :)
